@startuml

class Person {

    int O;
    int A;
    int B;
    int AB;

    int boolGroup();

}

class BloodGroup {
    BloodGroup O;
    BloodGroup A;
    BloodGroup B;
    BloodGroup AB;
}

PersonA --> BloodGroup


note as N1
  类之中有一个数值类型码，但是它并不影响类的行为。
  以一个新的类替换该数值类型码。
end note


@enduml